/**
 * Author: JIAYANG DAI
 * Student ID: 24664639
 * Email: j.dai.12@student.scu.edu.au
 * Assignment: PROG2005 Assessment 2 - Part 2
 * Description: Unit testing file for the HelpComponent. (Auto-generated by Angular CLI)
 */

import { ComponentFixture, TestBed } from '@angular/core/testing';
import { HelpComponent } from './help.component';

describe('HelpComponent', () => {
  let component: HelpComponent;
  let fixture: ComponentFixture<HelpComponent>;

  beforeEach(async () => {
    // Configure the testing module for this component
    await TestBed.configureTestingModule({
      declarations: [HelpComponent]
    })
    .compileComponents();
    
    fixture = TestBed.createComponent(HelpComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  // Basic auto-generated test to ensure the component initializes correctly
  it('should create', () => {
    expect(component).toBeTruthy();
  });
});