/**
 * Author: JIAYANG DAI
 * Student ID: 24664639
 * Email: j.dai.12@student.scu.edu.au
 * Assignment: PROG2005 Assessment 2 - Part 2
 * Description: Unit testing file for the ManageComponent. (Auto-generated by Angular CLI)
 */

import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ManageComponent } from './manage.component';

describe('ManageComponent', () => {
  let component: ManageComponent;
  let fixture: ComponentFixture<ManageComponent>;

  beforeEach(async () => {
    // Configure the testing module for the manage component
    await TestBed.configureTestingModule({
      declarations: [ManageComponent]
    })
    .compileComponents();
    
    fixture = TestBed.createComponent(ManageComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  // Basic test to ensure the component is instantiated correctly
  it('should create', () => {
    expect(component).toBeTruthy();
  });
});