/**
 * Author: JIAYANG DAI
 * Student ID: 24664639
 * Email: j.dai.12@student.scu.edu.au
 * Assignment: PROG2005 Assessment 2 - Part 2
 * Description: Unit testing file for the PrivacySecurityComponent. (Auto-generated by Angular CLI)
 */

import { ComponentFixture, TestBed } from '@angular/core/testing';
import { PrivacySecurityComponent } from './privacy-security.component';

describe('PrivacySecurityComponent', () => {
  let component: PrivacySecurityComponent;
  let fixture: ComponentFixture<PrivacySecurityComponent>;

  beforeEach(async () => {
    // Configure the testing module for the privacy and security component
    await TestBed.configureTestingModule({
      declarations: [PrivacySecurityComponent]
    })
    .compileComponents();
    
    fixture = TestBed.createComponent(PrivacySecurityComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  // Basic auto-generated test to ensure the component initializes correctly
  it('should create', () => {
    expect(component).toBeTruthy();
  });
});