/**
 * Author: JIAYANG DAI
 * Student ID: 24664639
 * Email: j.dai.12@student.scu.edu.au
 * Assignment: PROG2005 Assessment 2 - Part 2
 * Description: Unit testing file for the InventoryService. (Auto-generated by Angular CLI)
 */

import { TestBed } from '@angular/core/testing';
import { InventoryService } from './inventory.service';

describe('InventoryService', () => {
  let service: InventoryService;

  beforeEach(() => {
    // Configure the testing module for the inventory service
    TestBed.configureTestingModule({});
    service = TestBed.inject(InventoryService);
  });

  // Basic auto-generated test to ensure the service is instantiated correctly
  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});