/**
 * Author: JIAYANG DAI
 * Student ID: 24664639
 * Email: j.dai.12@student.scu.edu.au
 * Assignment: PROG2005 Assessment 2 - Part 2
 * Description: Unit testing file for the SearchComponent. (Auto-generated by Angular CLI)
 */

import { ComponentFixture, TestBed } from '@angular/core/testing';
import { SearchComponent } from './search.component';

describe('SearchComponent', () => {
  let component: SearchComponent;
  let fixture: ComponentFixture<SearchComponent>;

  beforeEach(async () => {
    // Configure the testing module for the search component
    await TestBed.configureTestingModule({
      declarations: [SearchComponent]
    })
    .compileComponents();
    
    fixture = TestBed.createComponent(SearchComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  // Basic auto-generated test to ensure the component initializes correctly
  it('should create', () => {
    expect(component).toBeTruthy();
  });
});